### PR TITLE
update cubecl for constant bitcasts

### PR DESCRIPTION
**Pull request by jcwal1516**
## Summary

Update CubeCL to tracel-ai/cubecl#1477 so constant bitcasts are materialized as lvalues in the C++ dialects. This restores CUDA, HIP, and Metal source generation for the infinity reduction identities introduced by #457.

Depends on tracel-ai/cubecl#1477.
Related to #457.

## Testing

- `cargo fmt --all --check` — passed.
- `cargo xtask check lint` — passed.
- `cargo xtask doc build` — passed with the existing rustdoc link warnings.
- `cargo xtask doc tests` — passed; 6 ignored, 0 failed.
- `cargo xtask test --ci` — 8,413 passed and 24 TopK-with-indices cases failed. An exact failing case also fails on untouched `origin/main` at `de661419` with CubeCL `5d5af999`, confirming the failures are pre-existing and unrelated to this pin.
- `cargo test-cuda -p cubek-reduce --test lib nan_extrema --locked -- --nocapture --test-threads=1` — 10 passed, 0 failed on an NVIDIA GeForce RTX 4070 SUPER.

## Validate your PR with burn.

It is important that you make sure that you don't introduce any bugs in burn. 

### Instructions

- [ ] Create a new branch or fork of the [burn repo](https://github.com/Tracel-AI/burn)
- [ ] Update the main [Cargo.toml](https://github.com/tracel-ai/burn/blob/40aa993fb5969351a006b560ec89da5119dc9721/Cargo.toml#L159=L161) with this PR hash.
- [ ] Fix any broken tests or compilation errors in burn.
- [ ] Submit a PR in burn with your fixes and link it here.

### CODE REVIEW

**Review by laggui — APPROVED** [review]
Merged the cubecl PR and updated the rev to move this forward
